### ISSUE TITLE
'TypeError: __init__() takes 2 positional arguments but 3 were given' when trying to show ROI on images

### ISSUE THREAD

**Issue by ZackLoken** [UTokyo-FieldPhenomics-Lab/EasyIDP#108]
`ms.show_roi_on_img(img_dict_ms, "N1W1", "DJI_0479")` returns: 

> TypeError                                 Traceback (most recent call last)
> Cell In[13], [line 1](vscode-notebook-cell:?execution_count=13&line=1)
> ----> [1](vscode-notebook-cell:?execution_count=13&line=1) ms.show_roi_on_img(img_dict_ms, "N1W1", "DJI_0479")
> 
> File [c:\Users\zack\anaconda3\envs\easyidp\lib\site-packages\easyidp\metashape.py:922](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:922), in Metashape.show_roi_on_img(self, img_dict, roi_name, img_name, **kwargs)
>     [919](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:919)     kwargs['show'] = True
>     [921](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:921) if img_name is not None:
> --> [922](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:922)     idp.visualize.draw_polygon_on_img(
>     [923](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:923)         img_name, 
>     [924](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:924)         img_path=self.photos[img_name].path, 
>     [925](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:925)         poly_coord=img_dict[roi_name][img_name], 
>     [926](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:926)         **kwargs
>     [927](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:927)         )
>     [928](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:928) else:
>     [929](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:929)     idp.visualize.draw_backward_one_roi(
>     [930](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:930)         self, img_dict[roi_name], 
>     [931](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:931)         **kwargs
>     [932](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/metashape.py:932)     )
> 
> File [c:\Users\zack\anaconda3\envs\easyidp\lib\site-packages\easyidp\visualize.py:160](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/visualize.py:160), in draw_polygon_on_img(img_name, img_path, poly_coord, corrected_poly_coord, title, save_as, show, color, alpha, dpi)
>     [157](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/visualize.py:157) ax[0].imshow(img_array)
>     [159](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/visualize.py:159) if corrected_poly_coord is None:
> --> [160](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/visualize.py:160)     polygon = pts.Polygon(poly_coord, True)
>     [161](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/visualize.py:161) else:
>     [162](file:///C:/Users/zack/anaconda3/envs/easyidp/lib/site-packages/easyidp/visualize.py:162)     polygon = pts.Polygon(corrected_poly_coord, True)
> 
> TypeError: __init__() takes 2 positional arguments but 3 were given

when trying to show ROIs on images in the Lotus example. Something is happening with the polygon coordinates, but I cannot resolve this. I followed your install instructions exactly as detailed, so I'm unsure why I can't get it to work with your sample data. Can you help?

**Comment by HowcanoeWang** [comment]
If you installed the EasyIDP via pip

```python
>>> import easyidp as idp
>>> idp.__version__
2.0.0.dev4
```

Please try if install from the latest source code fixed this issue:

https://easyidp.readthedocs.io/en/latest/install.html#using-from-source-code

This version should be:

```python
>>> idp.__version__
2.0.0
```

**Comment by ZackLoken** [comment]
Installing from the latest source code fixed this issue. Thank you so much!
